---
name: Test
on: [push, pull_request]

jobs:
  ruby:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["ruby-head", "3.3", "3.2", "3.1", "3.0", "2.7", "2.6"]
        gemfile: ["rack-2", "rack-3"]

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install packages
        run: sudo apt-get install -y ragel socat netcat

      - name: Tests ${{ matrix.rubyopt }}
        run: bundle exec rake
