---
name: Test
on: [push, pull_request]

jobs:
  ruby:
    name: Ruby ${{ matrix.ruby }}, Rack ${{ matrix.rack }} ${{ matrix.rubyopt }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["ruby-head", "3.3", "3.2", "3.1", "3.0", "2.7", "2.6"]
        rubyopt: [""]
        rack: ["~> 3.0"]
        include:
          - ruby: "3.3"
            rubyopt: "--enable-frozen-string-literal"
          # Rack versions
          - ruby: "2.6"
            rack: "2.0.0" # earliest support version
          - ruby: "3.3"
            rack: "~> 3.0.0"

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Apply Rack version
        run: echo "gem 'rack', '${{ matrix.rack }}'" >> Gemfile

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install packages
        run: sudo apt-get install -y ragel socat netcat

      - name: Tests ${{ matrix.rubyopt }}
        run: RUBYOPT="${{ matrix.rubyopt }}" bundle exec rake
